In [1]:
import numpy as np
import pandas as pd

In [9]:
#Random integer
arr1=np.random.randint(-100,100,size=(10))
print(arr1)
print("Dimension = ",arr1.ndim)

[-36  45 -79 -74  10 -97  56 -63  -1  -1]
Dimension =  1


In [8]:
# Random floats
arr2=np.random.sample(size=10)
print(arr2)
print("Dimension = ",arr2.ndim)

[6.77800521e-01 4.47476039e-01 5.82096666e-02 4.78269915e-01
 6.18655577e-04 4.68006431e-01 7.17423922e-01 2.50632421e-01
 5.56902332e-01 5.21256697e-01]
Dimension =  1


In [7]:
# Random complex numbers
arr3 = np.random.random(10) + np.random.random(10) * 1j
print(arr3)
print("Dimension = ",arr3.ndim)

[0.83452572+0.34035511j 0.6241225 +0.10409413j 0.08454265+0.21187205j
 0.67369123+0.62204345j 0.7332843 +0.34880129j 0.83063659+0.78395045j
 0.43646071+0.37733088j 0.80074565+0.5836597j  0.50038819+0.05113225j
 0.88227518+0.04625955j]
Dimension =  1


In [13]:
matrix = np.vstack((arr1,arr2,arr3))
print(matrix)
print("Dimension: ",matrix.ndim)

[[-3.60000000e+01+0.j          4.50000000e+01+0.j
  -7.90000000e+01+0.j         -7.40000000e+01+0.j
   1.00000000e+01+0.j         -9.70000000e+01+0.j
   5.60000000e+01+0.j         -6.30000000e+01+0.j
  -1.00000000e+00+0.j         -1.00000000e+00+0.j        ]
 [ 6.77800521e-01+0.j          4.47476039e-01+0.j
   5.82096666e-02+0.j          4.78269915e-01+0.j
   6.18655577e-04+0.j          4.68006431e-01+0.j
   7.17423922e-01+0.j          2.50632421e-01+0.j
   5.56902332e-01+0.j          5.21256697e-01+0.j        ]
 [ 8.34525724e-01+0.34035511j  6.24122501e-01+0.10409413j
   8.45426470e-02+0.21187205j  6.73691233e-01+0.62204345j
   7.33284303e-01+0.34880129j  8.30636587e-01+0.78395045j
   4.36460710e-01+0.37733088j  8.00745653e-01+0.5836597j
   5.00388191e-01+0.05113225j  8.82275177e-01+0.04625955j]]
Dimension:  2


In [14]:
m1=np.matrix('1 2 3;4 5 6;7 8 9')
m2=np.matrix('4 5 6;7 8 9;1 2 3')

In [15]:
print(m1+m2)

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]


In [16]:
m1.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [17]:
m1.dot(m2)

matrix([[ 21,  27,  33],
        [ 57,  72,  87],
        [ 93, 117, 141]])

In [18]:
np.multiply(m1,m2)

matrix([[ 4, 10, 18],
        [28, 40, 54],
        [ 7, 16, 27]])

In [20]:
#Slicing
print(arr1[2:5])
#reversing array
print(arr1[::-1])

[-79 -74  10]
[ -1  -1 -63  56 -97  10 -74 -79  45 -36]


In [21]:
df=pd.read_excel('https://github.com/ansharora23/Bennett-Sem5/blob/master/DeepLearning/Lab2/Data/Online%20Retail.xlsx?raw=true')
df=df[:100]

In [23]:
arr = df.values
arr

array([[536365, '85123A', 'WHITE HANGING HEART T-LIGHT HOLDER', 6,
        Timestamp('2010-12-01 08:26:00'), 2.55, 17850.0,
        'United Kingdom'],
       [536365, 71053, 'WHITE METAL LANTERN', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, '84406B', 'CREAM CUPID HEARTS COAT HANGER', 8,
        Timestamp('2010-12-01 08:26:00'), 2.75, 17850.0,
        'United Kingdom'],
       [536365, '84029G', 'KNITTED UNION FLAG HOT WATER BOTTLE', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, '84029E', 'RED WOOLLY HOTTIE WHITE HEART.', 6,
        Timestamp('2010-12-01 08:26:00'), 3.39, 17850.0,
        'United Kingdom'],
       [536365, 22752, 'SET 7 BABUSHKA NESTING BOXES', 2,
        Timestamp('2010-12-01 08:26:00'), 7.65, 17850.0,
        'United Kingdom'],
       [536365, 21730, 'GLASS STAR FROSTED T-LIGHT HOLDER', 6,
        Timestamp('2010-12-01 08:26:00'), 4.25, 17850.0,
        